### ISSUE TITLE
Error when starting: [serial] is an invalid option 

### ISSUE THREAD

**Issue by TheChicken14** [ksya/ha-nefiteasy#10]
Hi, I just installed the component, but when I restart HASS.IO it gives me this error:
```Invalid config for [nefiteasy]: [serial] is an invalid option for [nefiteasy]. Check: nefiteasy->nefiteasy->serial. (See /config/configuration.yaml, line 79).```

This is my config:
```yaml
nefiteasy:
  serial: '1234567'
  accesskey: abcdefg
  password: abcdefg
  name: Nefit Easy
  sensors:
    - status
    - supply_temperature
    - hot_water_operation
```

**Comment by ksya** [comment]
I just updated the component, configuration is a little different now. Please change it to this:

```
`nefiteasy:`
devices:
- serial: '1234567'
  accesskey: abcdefg
  password: abcdefg
  name: Nefit Easy
  sensors:
    - status
    - supply_temperature
    - hot_water_operation
```
