### ISSUE TITLE
Request for Monthly Consumption

### ISSUE THREAD

**Issue by Salvora** [ksya/ha-nefiteasy#35]
Currently Nefit sensor have the following value for the consumption
sensor.nefit_year_total

However, this is a yearly total. Is there a way to add a sensor for the monthly consumption for tracking the bills?

**Comment by RobBie1221** [comment]
Like this: https://www.home-assistant.io/integrations/utility_meter/ ?

**Comment by Salvora** [comment]
Yeah, kinda like this. Thanks for the suggestion. I will try that and see how it will go but I need to try that for a monthly cycle which will take time. Though, I was expecting something like a monthly gas usage sensor.
Configuration is set like that
```yaml
#UTILITY METER
utility_meter:
  gas:
    source: sensor.nefit_year_total
    cycle: monthly
```
