### ISSUE TITLE
Is there a way to set temp with a script in HA

### ISSUE THREAD

**Issue by TheGabeMan** [ksya/ha-nefiteasy#376]
Maybe I'm overlooking something very obvious, but I can't find a way to set the temperature. When I use the thermostat card on my dashboard, I can change the mode and set the temperature. But I'm searching of a way to do this through a script but keep getting errors: ```extra keys not allowed @ data['temperature']. Got None```.

For example with this code:
```yaml
action: climate.set_hvac_mode
target:
  device_id: 37e3a7d496fc7bae28b2006ae2b1fcea
data:
  hvac_mode: heat
  temperature: 19
``` 
Any tips on how to do this?
