### ISSUE TITLE
Ignores the Configuration and exposes all

### ISSUE THREAD

**Issue by Salvora** [ksya/ha-nefiteasy#42]
Just noticed this,

```yaml
nefiteasy:
  devices:
    - serial: !secret buderus_serial
      accesskey: !secret buderus_accesskey
      password: !secret buderus_password
      name: Combi
      sensors:
        - year_total
        - status
        - supply_temperature
        - outdoor_temperature
        # - system_pressure
        - active_program
        - hot_water_operation
      switches:
        - hot_water
        - holiday_mode
        #- fireplace_mode
        #- today_as_sunday
        #- tomorrow_as_sunday
        - preheating
        - home_entrance_detection
        - weather_dependent
        - lockui
```
According to the above config, 1 sensor and 3 switches are disabled but the addon ignores the configuration and exposes all of them.
![image](https://user-images.githubusercontent.com/6360098/106338793-c2aa5200-62a5-11eb-9f11-34aa955fe529.png)

Additionally, the "name" component doesn't seem to make a difference.

Can anybody else test this?
